---

name: Lint

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:

  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Lint the README
      - uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: README.md

      # Lint issue templates
      - uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .github/ISSUE_TEMPLATE/*.md

      # Lint pull request templates
      - uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .github/PULL_REQUEST_TEMPLATE.md

  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Lint all .yml files
      - uses: ibiqlik/action-yamllint@v3
        with:
          strict: true
          format: parsable
          config_data: |
            extends: default
            ignore:
              test/**/*.yml
            rules:
              line-length: disable
              truthy:
                check-keys: false
                allowed-values:
                  - "true"
                  - "false"
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Check all files against the .editorconfig
      - uses: editorconfig-checker/action-editorconfig-checker@v1.0.0
